alphabet_data = [
    {"letter": "A", "word": "Apple", "prompt": "A for Apple, cartoon style, colorful for kids"},
    {"letter": "B", "word": "Ball", "prompt": "B for Ball, cute and colorful, kids style"},
    {"letter": "C", "word": "Cat", "prompt": "C for Cat, cartoon cat, happy face"},
    {"letter": "D", "word": "Dog", "prompt": "D for Dog, playful cartoon dog, kid-friendly"},
    {"letter": "E", "word": "Elephant", "prompt": "E for Elephant, baby elephant cartoon, colorful"},
    {"letter": "F", "word": "Fish", "prompt": "F for Fish, cute colorful fish, underwater cartoon"},
    {"letter": "G", "word": "Giraffe", "prompt": "G for Giraffe, tall cartoon giraffe, smiling"},
    {"letter": "H", "word": "Hat", "prompt": "H for Hat, fun cartoon hat, colorful and bright"},
    {"letter": "I", "word": "Ice Cream", "prompt": "I for Ice Cream, colorful ice cream cone, cute and fun"},
    {"letter": "J", "word": "Juice", "prompt": "J for Juice, glass of cartoon orange juice, happy face"},
    {"letter": "K", "word": "Kite", "prompt": "K for Kite, flying cartoon kite, bright sky, colorful tail"},
    {"letter": "L", "word": "Lion", "prompt": "L for Lion, cartoon lion, big mane, smiling"},
    {"letter": "M", "word": "Monkey", "prompt": "M for Monkey, cartoon monkey hanging on tree, cute"},
    {"letter": "N", "word": "Nest", "prompt": "N for Nest, bird nest with eggs, cartoon style"},
    {"letter": "O", "word": "Orange", "prompt": "O for Orange, cartoon orange fruit, smiling, kid-friendly"},
    {"letter": "P", "word": "Penguin", "prompt": "P for Penguin, cute cartoon penguin on ice"},
    {"letter": "Q", "word": "Queen", "prompt": "Q for Queen, cartoon queen with crown, smiling"},
    {"letter": "R", "word": "Rabbit", "prompt": "R for Rabbit, cartoon bunny rabbit, holding carrot"},
    {"letter": "S", "word": "Sun", "prompt": "S for Sun, bright smiling cartoon sun, cheerful"},
    {"letter": "T", "word": "Tiger", "prompt": "T for Tiger, friendly cartoon tiger, colorful and cute"},
    {"letter": "U", "word": "Umbrella", "prompt": "U for Umbrella, cartoon umbrella in rain, colorful"},
    {"letter": "V", "word": "Van", "prompt": "V for Van, cartoon van on road, bright and playful"},
    {"letter": "W", "word": "Whale", "prompt": "W for Whale, big smiling cartoon whale, ocean scene"},
    {"letter": "X", "word": "Xylophone", "prompt": "X for Xylophone, colorful musical toy xylophone, cartoon style"},
    {"letter": "Y", "word": "Yacht", "prompt": "Y for Yacht, cartoon boat on water, colorful and fun"},
    {"letter": "Z", "word": "Zebra", "prompt": "Z for Zebra, friendly cartoon zebra in jungle"}
]
